version: '3'
services:
  noda: 
    container_name: noda
    build:
        context: .
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
      - ./src:/usr/src/app/src
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - task10postgres
    restart: always
    environment:
      - PORT=${PORT}
    command: npm run start:dev
  task10postgres:
    container_name: task10postgres
    build: ./db/
    image: avshell/postgres2021q4
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT_IN_CONTAINER}
    restart: always
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PORT_IN_CONTAINER=${POSTGRES_PORT_IN_CONTAINER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_log_volume:/logs
      - db_data_volume:/var/lib/postgresql/data
    networks:
      - custom-network

volumes: 
        db_data_volume:
        db_log_volume:
networks:
    custom-network:
        driver: bridge 