version: '3'
services:
  postgres:
    build: ./db/
    image: avshell/postgres2021q4
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT_IN_CONTAINER}
    restart: always
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PORT_IN_CONTAINER=${POSTGRES_PORT_IN_CONTAINER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_log_volume:/logs
      - db_data_volume:/var/lib/postgresql/data
    networks:
      - custom-network

volumes: 
        db_data_volume:
        db_log_volume:
networks:
    custom-network:
        driver: bridge 